nas_root_path: /Users/weibo/code/myself/anfm/tests
scan_option: 
  extensions: 
  - "jpg"
  regex_path:
  - ".*"
db_path: data/sqlite.db
cache_path: data/cache
dl_configuration:
  scheme: http
  host: localhost
  port: 8081
  timeout: 10